kind: pipeline
type: docker
name: pr-testing

platform:
  os: linux
  arch: amd64

steps:
- name: lint
  image: golangci/golangci-lint:v1.31.0-alpine
  commands:
  - golangci-lint run

trigger:
  event:
  - pull_request
