---
kind: pipeline
type: docker
name: pr-testing

platform:
  os: linux
  arch: amd64

steps:
- name: lint
  image: golangci/golangci-lint:v1.31.0-alpine
  commands:
  - golangci-lint run
  volumes:
  - name: gopath
    path: /go

- name: test
  image: golang:1.15.2-alpine3.12
  commands:
  - go test -cover ./...
  environment:
    CGO_ENABLED: 0
  volumes:
  - name: gopath
    path: /go

volumes:
- name: gopath
  temp: {}

trigger:
  event:
  - pull_request

---
