workspace:
  base: /go
  path: src/github.com/drone-plugins/drone-downstream

pipeline:
  test:
    image: golang:1.9
    pull: true
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out

  build_linux_amd64:
    image: golang:1.9
    pull: true
    group: build
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
    commands:
      - go build -v -ldflags "-X main.build=${DRONE_BUILD_NUMBER}" -a -o release/linux/amd64/drone-downstream

  build_linux_arm64:
    image: golang:1.9
    pull: true
    group: build
    environment:
      - GOOS=linux
      - GOARCH=arm64
      - CGO_ENABLED=0
    commands:
      - go build -v -ldflags "-X main.build=${DRONE_BUILD_NUMBER}" -a -o release/linux/arm64/drone-downstream

  build_linux_arm:
    image: golang:1.9
    pull: true
    group: build
    environment:
      - GOOS=linux
      - GOARCH=arm
      - CGO_ENABLED=0
      - GOARM=7
    commands:
      - go build -v -ldflags "-X main.build=${DRONE_BUILD_NUMBER}" -a -o release/linux/arm/drone-downstream

  # build_windows_amd64:
  #   image: golang:1.9-nanoserver
  #   pull: true
  #   group: build
  #   environment:
  #     - GOOS=windows
  #     - GOARCH=amd64
  #     - CGO_ENABLED=0
  #   commands:
  #     - go build -v -ldflags "-X main.build=${DRONE_BUILD_NUMBER}" -a -o release/windows/amd64/drone-downstream

  publish_linux_amd64:
    image: plugins/docker:17.05
    pull: true
    repo: plugins/downstream
    tags:
      - latest
      - 1.0
      - 1
      - 1.0.${DRONE_BUILD_NUMBER}
    secrets: [ docker_username, docker_password ]
    dockerfile: Dockerfile
    when:
      branch: master
      event: push

  publish_linux_arm64:
    image: plugins/docker:17.05
    pull: true
    repo: plugins/downstream
    tags: [ linux-arm64 ]
    secrets: [ docker_username, docker_password ]
    dockerfile: Dockerfile.arm64
    when:
      branch: master
      event: push

  publish_linux_arm:
    image: plugins/docker:17.05
    pull: true
    repo: plugins/downstream
    tags: [ linux-arm ]
    secrets: [ docker_username, docker_password ]
    dockerfile: Dockerfile.arm
    when:
      branch: master
      event: push

  # publish_windows_amd64:
  #   image: plugins/docker:17.05
  #   pull: true
  #   repo: plugins/downstream
  #   tags: [ windows-amd64 ]
  #   secrets: [ docker_username, docker_password ]
  #   dockerfile: Dockerfile.windows
  #   when:
  #     branch: master
  #     event: push

  microbadger:
    image: plugins/webhook:1
    pull: true
    secrets: [ webhook_url ]
    when:
      branch: master
      event: push
      status: [ success ]
