# escape=`
FROM plugins/base:windows-2004-amd64

LABEL maintainer="Grafana Labs <info@grafana.com>" `
  org.label-schema.name="Drone Downstream" `
  org.label-schema.vendor="Grafana Labs" `
  org.label-schema.schema-version="1.0"

COPY release/windows/amd64/drone-downstream.exe C:/bin/drone-downstream.exe
ENTRYPOINT ["C:\\bin\\drone-downstream.exe"]
