FROM plugins/base:multiarch

LABEL maintainer="Grafana Labs <info@grafana.com>" \
  org.label-schema.name="Drone Downstream" \
  org.label-schema.vendor="Grafana Labs" \
  org.label-schema.schema-version="1.0"

COPY release/linux/arm64/drone-downstream /bin/
ENTRYPOINT ["/bin/drone-downstream"
